stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet build --configuration Release
    - dontet publish --no-build --no-restore --configuration Release --output $CI_PROJECT_DIR/publish/ #публикация проекта
  only:
    - NewBranch


test-job:
    stage: test
    script:
      - echo "Running test job"
